// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_O3_Vdv16W1DihbIaPJKyIhfOL2Hpy9w',
    appId: '1:965259652279:web:7adc89425b02b972b53132',
    messagingSenderId: '965259652279',
    projectId: 'sothern-tour-app',
    authDomain: 'sothern-tour-app.firebaseapp.com',
    databaseURL: 'https://sothern-tour-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sothern-tour-app.appspot.com',
    measurementId: 'G-EL7N6J2QNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBImkPW1LEG1OcpPmIFwm-Yn_U-Zx-0gTw',
    appId: '1:965259652279:android:1eb8eeb74e649aeeb53132',
    messagingSenderId: '965259652279',
    projectId: 'sothern-tour-app',
    databaseURL: 'https://sothern-tour-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sothern-tour-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCPxsawA2RbxNkaPAN8gP1guGObnUickk',
    appId: '1:965259652279:ios:b134b29d650fb7ebb53132',
    messagingSenderId: '965259652279',
    projectId: 'sothern-tour-app',
    databaseURL: 'https://sothern-tour-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sothern-tour-app.appspot.com',
    iosClientId: '965259652279-mcku1ssvg18h0tvpkl9282tth6b3rm6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.southernTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCPxsawA2RbxNkaPAN8gP1guGObnUickk',
    appId: '1:965259652279:ios:b134b29d650fb7ebb53132',
    messagingSenderId: '965259652279',
    projectId: 'sothern-tour-app',
    databaseURL: 'https://sothern-tour-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sothern-tour-app.appspot.com',
    iosClientId: '965259652279-mcku1ssvg18h0tvpkl9282tth6b3rm6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.southernTour',
  );
}
